# Generated by Django 4.2.30 on 2026-06-09 01:02

from django.db import migrations, models


def flush_geo_areas(apps, schema_editor):
    """Re-key cutover to the INTL ("New*Cod") scheme.

    The old integer pcodes have no generic mapping to the INTL scheme, and the
    pcode AlterField below would otherwise cast them to decimal strings
    ("30101") that are indistinguishable from real INTL codes ("010106") yet are
    not INTL codes. To leave *only* INTL codes representable, drop every row here
    rather than cast it; re-run ``manage.py import_timor_geo_data`` after
    migrating to repopulate from the committed INTL-keyed data. Child-first order
    satisfies the ``on_delete=PROTECT`` foreign keys.
    """
    for model_name in ("Aldeia", "Suco", "AdministrativePost", "Municipality"):
        apps.get_model("timor_locations", model_name).objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('timor_locations', '0007_aldeia_delete_edgemap_delete_timortopology'),
    ]

    operations = [
        # Cutover first: empty the tables so the pcode type change below operates
        # on zero rows and no stringified-integer code can survive the re-key.
        migrations.RunPython(flush_geo_areas, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='administrativepost',
            name='pcode',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aldeia',
            name='pcode',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='pcode',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='suco',
            name='pcode',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
