# Generated by Django 4.2.30 on 2026-06-09 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timor_locations', '0007_aldeia_delete_edgemap_delete_timortopology'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativepost',
            name='legacy_pcode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aldeia',
            name='legacy_pcode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='legacy_pcode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suco',
            name='legacy_pcode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='administrativepost',
            name='pcode',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aldeia',
            name='pcode',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='pcode',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='suco',
            name='pcode',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
